class Darimi{
   int? number;
  String? arab;
  String? id;

 Darimi({this.number, this.arab, this.id});
}
var dataHadits = [
   Darimi(
    number : 1,
    arab : " حَدَّثَنَا مُحَمَّدُ بْنُ يُوسُفَ عَنْ سُفْيَانَ عَنْ الْأَعْمَشِ عَنْ أَبِي وَائِلٍ عَنْ عَبْدِ اللَّهِ قَالَ جَاءَ رَجُلٌ إِلَى رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ يَا رَسُولَ اللَّهِ أَيُؤَاخَذُ الرَّجُلُ بِمَا عَمِلَ فِي الْجَاهِلِيَّةِ قَالَ مَنْ أَحْسَنَ فِي الْإِسْلَامِ لَمْ يُؤَاخَذْ بِمَا كَانَ عَمِلَ فِي الْجَاهِلِيَّةِ وَمَنْ أَسَاءَ فِي الْإِسْلَامِ أُخِذَ بِالْأَوَّلِ وَالْآخِرِ",
    id : "Telah menceritakan kepada kami [Muhammad bin Yusuf] dari [Sufyan] dari [Al A'masy] dari [Abu Wa`il] dari [Abdullah], ia berkata; Datang kepada Rasulullah shallallahu 'alaihi wasallam seorang laki-laki lalu berkata: Wahai Rasulullah apakah seseorang akan dihukum atas perbuatan jelek yang dilakukannya pada masa jahiliyah? Rasul pun menjawab: Barang siapa yang berkelakuan baik pada masa Islamnya, ia tidak dihukum atas perbuatan jeleknya dimasa jahiliyah, tetapi barang siapa yang berkelakuan tidak baik (jahat) pada masa Islamnya, dia dihukum (atas dosanya) baik yang lalu ataupun yang selanjutnya. "
  ),
 Darimi(
    number : 2,
    arab : " أَخْبَرَنَا الْوَلِيدُ بْنُ النَّضْرِ الرَّمْلِيُّ عَنْ مَسَرَّةَ بْنِ مَعْبَدٍ مِنْ بَنِي الْحَارِثِ بْنِ أَبِي الْحَرَامِ مِنْ لَخْمٍ عَنْ الْوَضِينِ أَنَّ رَجُلًا أَتَى النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ يَا رَسُولَ اللَّهِ إِنَّا كُنَّا أَهْلَ جَاهِلِيَّةٍ وَعِبَادَةِ أَوْثَانٍ فَكُنَّا نَقْتُلُ الْأَوْلَادَ وَكَانَتْ عِنْدِي ابْنَةٌ لِي فَلَمَّا أَجَابَتْ وَكَانَتْ مَسْرُورَةً بِدُعَائِي إِذَا دَعَوْتُهَا فَدَعَوْتُهَا يَوْمًا فَاتَّبَعَتْنِي فَمَرَرْتُ حَتَّى أَتَيْتُ بِئْرًا مِنْ أَهْلِي غَيْرَ بَعِيدٍ فَأَخَذْتُ بِيَدِهَا فَرَدَّيْتُ بِهَا فِي الْبِئْرِ وَكَانَ آخِرَ عَهْدِي بِهَا أَنْ تَقُولَ يَا أَبَتَاهُ يَا أَبَتَاهُ فَبَكَى رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ حَتَّى وَكَفَ دَمْعُ عَيْنَيْهِ فَقَالَ لَهُ رَجُلٌ مِنْ جُلَسَاءِ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَحْزَنْتَ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ لَهُ كُفَّ فَإِنَّهُ يَسْأَلُ عَمَّا أَهَمَّهُ ثُمَّ قَالَ لَهُ أَعِدْ عَلَيَّ حَدِيثَكَ فَأَعَادَهُ فَبَكَى حَتَّى وَكَفَ الدَّمْعُ مِنْ عَيْنَيْهِ عَلَى لِحْيَتِهِ ثُمَّ قَالَ لَهُ إِنَّ اللَّهَ قَدْ وَضَعَ عَنْ الْجَاهِلِيَّةِ مَا عَمِلُوا فَاسْتَأْنِفْ عَمَلَكَ",
    id : "Telah mengabarkan kepada kami [Al Walid bin An Nadlr Ar Ramli] dari [Masarrah bin Ma'bad] -dari Bani Al Harits bin Abu Al Haram dari Lakhmin- dari [Al Wadliin] Bahwa seorang laki-laki datang kepada Nabi shallallahu 'alaihi wasallam lalu berkata: Hai Rasulullah, kami dahulu adalah orang-orang jahiliyah penyembah berhala dan kami membunuh anak-anak kami, ketika itu kami mempunyai anak yang senang apabila saya memanggilnya. Suatu hari saya pun memanggilnya dan dia langsung menyahut dan mengikuti saya. Ketika saya sampai di sebuah sumur keluarga, saya langsung memegang tangannya dan saya ceburkan dia ke sumur, itulah akhir kebersamaan saya dengannya. Dia memanggil 'wahai ayahku, wahai ayahku. ' Rasulullah pun menangis sampai air matanya bercucuran. Lalu seseeorang yang duduk-duduk bersama Rasulullah shallallahu 'alaihi wasallam berkata kepada laki-laki tersebut: kamu telah membuat Rasulullah shallallahu 'alaihi wasallam sedih. Rasulullah shallallahu 'alaihi wasallam berkata kepada orang tersebut: biarkan dia karena dia bertanya tentang sesuatu yang penting yang dihadapinya, kemudian Rasul berkata kepada laki-laki tersebut: Ulangi lagi cerita kamu tadi, lalu dia pun mengulangi ceritanya dan Rasul menangis lagi sampai bercucuran air matanya, membasahi jenggotnya, lalu beliau bersabda: Allah subhanahu wata'ala telah menghapus dosa-dosa yang dilakukan pada masa jahiliyah oleh karena itu mulailah perbuatan kamu dengan lembaran baru yang bersih. "
  ),
 Darimi(
    number : 3,
    arab : " أَخْبَرَنَا هَارُونُ بْنُ مُعَاوِيَةَ عَنْ إِبْرَاهِيمَ بْنِ سُلَيْمَانَ الْمُؤَدِّبِ عَنْ الْأَعْمَشِ عَنْ مُجَاهِدٍ قَالَ حَدَّثَنِي مَوْلَايَ أَنَّ أَهْلَهُ بَعَثُوا مَعَهُ بِقَدَحٍ فِيهِ زُبْدٌ وَلَبَنٌ إِلَى آلِهَتِهِمْ قَالَ فَمَنَعَنِي أَنْ آكُلَ الزُّبْدَ لِمَخَافَتِهَا قَالَ فَجَاءَ كَلْبٌ فَأَكَلَ الزُّبْدَ وَشَرِبَ اللَّبَنَ ثُمَّ بَالَ عَلَى الصَّنَمِ وَهُوَ إِسَافٌ وَنَائِلَةُ قَالَ هَارُونُ كَانَ الرَّجُلُ فِي الْجَاهِلِيَّةِ إِذَا سَافَرَ حَمَلَ مَعَهُ أَرْبَعَةَ أَحْجَارٍ ثَلَاثَةً لِقِدْرِهِ وَالرَّابِعَ يَعْبُدُهُ وَيُرَبِّي كَلْبَهُ وَيَقْتُلُ وَلَدَهُ",
    id : "Telah mengabarkan kepada kami [Harun bin Mu`awiyah] dari [Ibrahim bin sulaiman Al Mu`addib] dari [Al A'masy] dari [Mujahid], [bekas budakku] menceritakan kepadaku; bahwa keluarganya menitip sebuah wadah yang berisi keju dan susu untuk dipersembahkan kepada tuhan-tuhan mereka, ia berkata; keluargaku melarangku makan keju karena takut kepada tuhan-tuhan tersebut; lalu datanglah seekor anjing, memakan keju dan meminum susu serta kencing di atas patung-patung tersebut yaitu patung Iqaf dan nailah. Harun berkata: pada masa jahiliyah dulu apabila seorang laki-laki hendak bepergian dia akan mengikusertakan empat buah batu, tiga diantaranya untuk menopang/menegakan priuk (kuali/bejana) dan yang keempatnya untuk ia sembah, untuk melatih anjingnya, serta untuk membunuh anaknya. "
  ),
 Darimi(
    number : 4,
    arab : " حَدَّثَنَا مُجَاهِدُ بْنُ مُوسَى حَدَّثَنَا رَيْحَانُ هُوَ ابْنُ سَعِيدٍ السَّامِيُّ حَدَّثَنَا عَبَّادٌ هُوَ ابْنُ مَنْصُورٍ عَنْ أَبِي رَجَاءٍ قَالَ كُنَّا فِي الْجَاهِلِيَّةِ إِذَا أَصَبْنَا حَجَرًا حَسَنًا عَبَدْنَاهُ وَإِنْ لَمْ نُصِبْ حَجَرًا جَمَعْنَا كُثْبَةً مِنْ رَمْلٍ ثُمَّ جِئْنَا بِالنَّاقَةِ الصَّفِيِّ فَتَفَاجُّ عَلَيْهَا فَنَحْلُبُهَا عَلَى الْكُثْبَةِ حَتَّى نَرْوِيَهَا ثُمَّ نَعْبُدُ تِلْكَ الْكُثْبَةَ مَا أَقَمْنَا بِذَلِكَ الْمَكَانِ قَالَ أَبُو مُحَمَّد الصَّفِيُّ الْكَثِيرَةُ الْأَلْبَانِ",
    id : "Telah menceritakan kepada kami [Mujahid bin Musa] telah menceritakan kepada kami [Raihan Ibnu Sa'id As Sami] telah menceritakan kepada kami ['Abbad Ibnu Manshur] dari [Abu Raja`], ia berkata: kami dulu pada masa jahiliyah apabila menemukan batu yang bagus, kami pun menyembahnya dan apabila tidak mendapatkan yang bagus, kami pun mengumpulkan pasir. Kemudian kami mendatangkan onta yang shafi, ketika onta tersebut sudah mengangkanginya kamipun memeras susunya untuk menyirami tumpukan pasir yang kami kumpulkan, kemudian kami menyembah tumpukan pasir tersebut selama kami tinggal di tempat tersebut. Abu Muhammad berkata: onta shafi adalah onta yang banyak susunya. "
  ),
 Darimi(
    number : 5,
    arab : " أَخْبَرَنَا الْحَسَنُ بْنُ الرَّبِيعِ حَدَّثَنَا أَبُو الْأَحْوَصِ عَنْ الْأَعْمَشِ عَنْ أَبِي صَالِحٍ قَالَ قَالَ كَعْبٌ نَجِدُهُ مَكْتُوبًا مُحَمَّدٌ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ لَا فَظٌّ وَلَا غَلِيظٌ وَلَا صَخَّابٌ بِالْأَسْوَاقِ وَلَا يَجْزِي بِالسَّيِّئَةِ السَّيِّئَةَ وَلَكِنْ يَعْفُو وَيَغْفِرُ وَأُمَّتُهُ الْحَمَّادُونَ يُكَبِّرُونَ اللَّهَ عَزَّ وَجَلَّ عَلَى كُلِّ نَجْدٍ وَيَحْمَدُونَهُ فِي كُلِّ مَنْزِلَةٍ وَيَتَأَزَّرُونَ عَلَى أَنْصَافِهِمْ وَيَتَوَضَّئُونَ عَلَى أَطْرَافِهِمْ مُنَادِيهِمْ يُنَادِي فِي جَوِّ السَّمَاءِ صَفُّهُمْ فِي الْقِتَالِ وَصَفُّهُمْ فِي الصَّلَاةِ سَوَاءٌ لَهُمْ بِاللَّيْلِ دَوِيٌّ كَدَوِيِّ النَّحْلِ وَمَوْلِدُهُ بِمَكَّةَ وَمُهَاجِرُهُ بِطَابَةَ وَمُلْكُهُ بِالشَّامِ",
    id : "Telah mengabarkan kepada kami [Al Hasan bin Ar Rabi'] telah menceritakan kepada kami [Abul Ahwash] dari [Al A'masy] dari [Abu Shalih], ia berkata; [Ka'ab] berkata; kami mendapatinya tertulis: Muhammad Rasulullah shallallahu 'alaihi wasallam, beliau tidak kasar tutur katanya, tidak keras wataknya, tidak bersuara keras ketika di pasar, tidak membalas kejelekan dengan kejelekan, tetapi membalasnya dengan memaafkan dan mengampuni, umatnya adalah orang-orang yang selalu bertahmid (memuji Allah) bertakbir (mengagungkan Allah) disetiap tempat yang tinggi /pendakian, atau peperangan, mereka memuji Allah Subhanahu wa Ta'ala di tiap-tiap rumah, mengenakan sarung pada bagian tengah mereka, berwudlu pada setiap anggota wudlu mereka, panggilan adzan mereka terdengar di langit, shaf mereka pada waktu perang seperti shaf mereka pada waktu shalat, suara mereka (ketika membaca Al Quran dan berdzikir) bagaikan gemuruh suara lebah, tempat kelahiran beliau di Makkah dan tempat hijrahnya di thaabah (Madinah) dan kerajaannya berada di Syam. "
  ),
 Darimi(
    number : 6,
    arab : " حَدَّثَنَا عَبْدُ اللَّهِ بْنُ صَالِحٍ حَدَّثَنِي اللَّيْثُ حَدَّثَنِي خَالِدٌ هُوَ ابْنُ يَزِيدَ عَنْ سَعِيدٍ هُوَ ابْنُ أَبِي هِلَالٍ عَنْ هِلَالِ بْنِ أُسَامَةَ عَنْ عَطَاءِ بْنِ يَسَارٍ عَنْ ابْنِ سَلَامٍ أَنَّهُ كَانَ يَقُولُ إِنَّا لَنَجِدُ صِفَةَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ إِنَّا أَرْسَلْنَاكَ شَاهِدًا وَمُبَشِّرًا وَنَذِيرًا وَحِرْزًا لِلْأُمِّيِّينَ أَنْتَ عَبْدِي وَرَسُولِي سَمَّيْتُهُ الْمُتَوَكِّلَ لَيْسَ بِفَظٍّ وَلَا غَلِيظٍ وَلَا صَخَّابٍ بِالْأَسْوَاقِ وَلَا يَجْزِي بِالسَّيِّئَةِ مِثْلَهَا وَلَكِنْ يَعْفُو وَيَتَجَاوَزُ وَلَنْ أَقْبِضَهُ حَتَّى نُقِيمَ الْمِلَّةَ الْمُتَعَوِّجَةَ بِأَنْ تَشْهَدَ أَنْ لَا إِلَهَ إِلَّا اللَّهُ يَفْتَحُ بِهِ أَعْيُنًا عُمْيًا وَآذَانًا صُمًّا وَقُلُوبًا غُلْفًا قَالَ عَطَاءُ بْنُ يَسَارٍ وَأَخْبَرَنِي أَبُو وَاقِدٍ اللَّيْثِيُّ أَنَّهُ سَمِعَ كَعْبًا يَقُولُ مِثْلَ مَا قَالَ ابْنُ سَلَامٍ",
    id : "Telah menceritakan kepada kami [Abdullah bin Shalih] telah menceritakan kepadaku [Al Laits] telah menceritakan kepadaku [Khalid Ibnu Yazid] dari [Sa'id Ibnu Abu Hilal] dari [Hilal bin Usamah] dari ['Atha' bin Yasar] dari [Ibnu Salam], bahwa ia berkata; kami mendapati sifat Rasulullah shallallahu 'alaihi wasallam 'Sesungguhnya Kami mengutus kamu sebagai saksi, pemberi kabar gembira dan sebagai pemberi peringatan', yang menolong orang ummi, engkau adalah hambaKu RasulKu, Aku menamakannya Al Mutawakkil, tutur katanya tidak kasar dan perangainya tidak keras, tidak berteriak-teriak di pasar dan tidak membalas kejelekan dengan kejelekan, akan tetapi dengan memaafkannya sehingga kami meluruskan agama yang melenceng kepada persaksian bahwa tidak ada tuhan yang berhak disembah selain Allah Subhanahu wa Ta'ala, dengan persaksian tersebut kita dapat membuka mata yang buta, telinga-telinga yang pekak dan hati-hati yang tertutup. ['Atha` bin Yasar] berkata; [Abu waqid Al Laitsi] memberitahukan kepada saya bahwa ia mendengar [Ka'ab] juga berkata seperti apa yang dikatakan Ibnu salam. "
  ),
 Darimi(
    number : 7,
    arab : " أَخْبَرَنَا زَيْدُ بْنُ عَوْفٍ قَالَ وَحَدَّثَنَا أَبُو عَوَانَةَ عَنْ عَبْدِ الْمَلِكِ بْنِ عُمَيْرٍ عَنْ ذَكْوَانَ أَبِي صَالِحٍ عَنْ كَعْبٍ فِي السَّطْرِ الْأَوَّلِ مُحَمَّدٌ رَسُولُ اللَّهِ عَبْدِي الْمُخْتَارُ لَا فَظٌّ وَلَا غَلِيظٌ وَلَا صَخَّابٌ فِي الْأَسْوَاقِ وَلَا يَجْزِي بِالسَّيِّئَةِ السَّيِّئَةَ وَلَكِنْ يَعْفُو وَيَغْفِرُ مَوْلِدُهُ بِمَكَّةَ وَهِجْرَتُهُ بِطَيْبَةَ وَمُلْكُهُ بِالشَّامِ وَفِي السَّطْرِ الثَّانِي مُحَمَّدٌ رَسُولُ اللَّهِ أُمَّتُهُ الْحَمَّادُونَ يَحْمَدُونَ اللَّهَ فِي السَّرَّاءِ وَالضَّرَّاءِ يَحْمَدُونَ اللَّهَ فِي كُلِّ مَنْزِلَةٍ وَيُكَبِّرُونَ عَلَى كُلِّ شَرَفٍ رُعَاةُ الشَّمْسِ يُصَلُّونَ الصَّلَاةَ إِذَا جَاءَ وَقْتُهَا وَلَوْ كَانُوا عَلَى رَأْسِ كُنَاسَةٍ وَيَأْتَزِرُونَ عَلَى أَوْسَاطِهِمْ وَيُوَضِّئُونَ أَطْرَافَهُمْ وَأَصْوَاتُهُمْ بِاللَّيْلِ فِي جَوِّ السَّمَاءِ كَأَصْوَاتِ النَّحْلِ",
    id : "Telah mengabarkan kepada kami [Zaid bin Yusuf] telah menceritakan kepada kami [Abu 'Awanah] dari [Abdul malik bin Umair] dari [Dzakwan Abu Shalih] dari [Ka'ab] bahwa pada alinea pertama tertulis; Muhammad adalah utusan Allah Subhanahu wa Ta'ala, dan hambaKu yang terpilih, tutur katanya tidak kasar, perangainya tidak keras, tidak bersuara lantang di pasar, tidak membalas kejelekan dengan kejelekan akan tetapi membalasnya dengan pemberian maaf dan ampunan, tempat kelahirannya di Makkah dan tempat hijrahnya di Thaibah serta kerajaannya/kekuasaannya di Syam. Dan pada alenia kedua tertulis, Muhammad utusan Allah Subhanahu wa Ta'ala umatnya adalah orang-orang yang selalu memuji Allah atas segala kemuliaan, para pemantau matahari (untuk mengetahui waktu shalat) menunaikan shalat saat tiba waktunya, meskipun mereka di saat berada pada tempat yang kotor, mengenakan sarung pada bagian tengah, membasuh wudlu pada seluruh anggota wudlu, dan suara mereka di malam hari terdengar di udara bagaikan gemuruh suara lebah (karena kegigihan ibadah dan tangisnya). "
  ),
 Darimi(
    number : 8,
    arab : " أَخْبَرَنَا مُجَاهِدُ بْنُ مُوسَى حَدَّثَنَا مَعْنُ بْنُ عِيسَى حَدَّثَنَا مُعَاوِيَةُ بْنُ صَالِحٍ عَنْ أَبِي فَرْوَةَ عَنْ ابْنِ عَبَّاسٍ أَنَّهُ سَأَلَ كَعْبَ الْأَحْبَارِ كَيْفَ تَجِدُ نَعْتَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِي التَّوْرَاةِ فَقَالَ كَعْبٌ نَجِدُهُ مُحَمَّدُ بْنُ عَبْدِ اللَّهِ يُولَدُ بِمَكَّةَ وَيُهَاجِرُ إِلَى طَابَةَ وَيَكُونُ مُلْكُهُ بِالشَّامِ وَلَيْسَ بِفَحَّاشٍ وَلَا صَخَّابٍ فِي الْأَسْوَاقِ وَلَا يُكَافِئُ بِالسَّيِّئَةِ السَّيِّئَةَ وَلَكِنْ يَعْفُو وَيَغْفِرُ أُمَّتُهُ الْحَمَّادُونَ يَحْمَدُونَ اللَّهَ فِي كُلِّ سَرَّاءَ وَضَرَّاءَ وَيُكَبِّرُونَ اللَّهَ عَلَى كُلِّ نَجْدٍ يُوَضِّئُونَ أَطْرَافَهُمْ وَيَأْتَزِرُونَ فِي أَوْسَاطِهِمْ يُصَفُّونَ فِي صَلَوَاتِهِمْ كَمَا يُصَفُّونَ فِي قِتَالِهِمْ دَوِيُّهُمْ فِي مَسَاجِدِهِمْ كَدَوِيِّ النَّحْلِ يُسْمَعُ مُنَادِيهِمْ فِي جَوِّ السَّمَاءِ",
    id : "Telah mengabarkan kepada kami [Mujahid biun Musa] telah menceritakan kepada kami [Ma'n ibnu 'Isa] telah menceritakan kepada kami [Mu'awiyah bin Shalih] dari [Abu Farwah] dari [Ibnu 'Abbas] Radliyallahu'anhu, bahwa ia bertanya kepada Ka'ab Al Ahbar; Bagaimana kamu dapati sifat Rasulullah shallallahu 'alaihi wasallam dalam kitab Taurat?, [Ka'ab] menjawab; kami dapati ia Muhammad bin Abdullah dilahirkan di Makkah, berhijrah ke Thaabah atau Madinah, kerajaannya akan ada di Syam, ia bukan orang keji, ia tidak bersuara keras di pasar, ia tidak membalas kejelekan dengan kejelekan tetapi memaafkan dan mengampuni, umatnya senantiasa memuji. Mereka memuji Allah Subhanahu wa Ta'ala baik dalam keadaan senang atau susah, mereka selalu mengagungkan Allah Subhanahu wa Ta'ala dalam setiap kemenangan, mereka membasuh anggota wudlu mereka, mengenakan kain sarung pada bagian tengah mereka, bereka berbaris dalam shalat seperti berbarisnya mereka dalam peperangan, suara mereka di masjid-masjid mereka seperti gemuruh suara lebah, terdengar suara mu`dzin mereka di angkasa. "
  ),
 Darimi(
    number : 9,
    arab : " أَخْبَرَنَا حَيْوَةُ بْنُ شُرَيْحٍ حَدَّثَنَا بَقِيَّةُ بْنُ الْوَلِيدِ الْمِيثَمِيُّ حَدَّثَنَا بَحِيرُ بْنُ سَعْدٍ عَنْ خَالِدِ بْنِ مَعْدَانَ عَنْ جُبَيْرِ بْنِ نُفَيْرٍ الْحَضْرَمِيِّ أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ لَقَدْ جَاءَكُمْ رَسُولٌ إِلَيْكُمْ لَيْسَ بِوَهِنٍ وَلَا كَسِلٍ لِيَخْتِنَ قُلُوبًا غُلْفًا وَيَفْتَحَ أَعْيُنًا عُمْيًا وَيُسْمِعَ آذَانًا صُمًّا وَيُقِيمَ أَلْسِنَةً عُوجًا حَتَّى يُقَالَ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ",
    id : "Telah mengabarkan kepada kami [Haiwah bin Syuraih] telah menceritakan kepada kami [Baqiyyah bin Al Walid Al Maitami] telah menceritakan kepada kami [Buhair bin Sa'ad] dari [Khalid bin Ma'dan] dari [Jubair bin Nufair Al Hadlrami]; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Telah datang kepada kalian seorang utusan yang tidak lemah dan juga tidak malas, (diutus untuk) menyadarkan hati-hati yang lalai, membuka mata yang tertutup, dan menjadikan telinga-telinga yang tuli mendengar, meluruskan lisan yang bengkok, sehingga dikatakan; tiada tuhan yang berhak disembah melainkan Allah Subhanahu wa Ta'ala saja. "
  ),
 Darimi(
    number : 10,
    arab : " أَخْبَرَنَا مُحَمَّدُ بْنُ يَزِيدَ الْحِزَامِيُّ حَدَّثَنَا إِسْحَقُ بْنُ سُلَيْمَانَ عَنْ عَمْرِو بْنِ أَبِي قَيْسٍ عَنْ عَطَاءٍ قَالَ كَانَ رَجُلٌ مِنْ أَصْحَابِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ لَهُ إِلَيْهِ حَاجَةٌ فَمَشَى مَعَهُ حَتَّى دَخَلَ قَالَ فَإِحْدَى رِجْلَيْهِ فِي الْبَيْتِ وَالْأُخْرَى خَارِجَهُ كَأَنَّهُ يُنَاجِي فَالْتَفَتَ فَقَالَ أَتَدْرِي مَنْ كُنْتُ أُكَلِّمُ إِنَّ هَذَا مَلَكٌ لَمْ أَرَهُ قَطُّ قَبْلَ يَوْمِي هَذَا اسْتَأْذَنَ رَبَّهُ أَنْ يُسَلِّمَ عَلَيَّ قَالَ إِنَّا آتَيْنَاكَ أَوْ أَنْزَلْنَا الْقُرْآنَ فَصْلًا وَالسَّكِينَةَ صَبْرًا وَالْفُرْقَانَ وَصْلًا",
    id : "Telah mengabarkan kepada kami [Muhammad bin Yazid Al Hizami] telah menceritakan kepada kami [Ishaq bin Sulaiman] dari ['Amr bin Abu Qais] dari ['Atha`], ia berkata; Salah seorang sahabat Nabi shallallahu 'alaihi wasallam mempunyai keperluan dengan beliau. Ia berjalan bersama beliau, sampai ketika sudah memasuki rumah dan salah satu kaki beliau berada di dalam dan yang lainnya di luar rumah, seakan-akan Rasulullah shallallahu 'alaihi wasallam bercakap-cakap dengan seorang laki-laki, setelah itu beliau menoleh dan berbicara kepada sahabat tersebut: Tahukah anda siapa yang aku ajak bicara? dia adalah malaikat yang aku belum pernah melihatnya sebelum ini, malaikat tersebut meminta izin Rabbnya agar dapat mengucapkan salam kepadaku. Allah berfirman: \"Sesungguhnya kami mendatangimu atau menurunkan Al Qur'an sebagai pemutus perkara dan As Sakinah sebagai kesabaran dan Al Furqon sebagai pedoman. "
  ),
 Darimi(
    number : 11,
    arab : " أَخْبَرَنَا مُجَاهِدُ بْنُ مُوسَى حَدَّثَنَا رَيْحَانُ هُوَ ابْنُ سَعِيدٍ حَدَّثَنَا عَبَّادٌ هُوَ ابْنُ مَنْصُورٍ عَنْ أَيُّوبَ عَنْ أَبِي قِلَابَةَ عَنْ عَطِيَّةَ أَنَّهُ سَمِعَ رَبِيعَةَ الْجُرَشِيَّ يَقُولُ أُتِيَ النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقِيلَ لَهُ لِتَنَمْ عَيْنُكَ وَلْتَسْمَعْ أُذُنُكَ وَلْيَعْقِلْ قَلْبُكَ قَالَ فَنَامَتْ عَيْنَايَ وَسَمِعَتْ أُذُنَايَ وَعَقَلَ قَلْبِي قَالَ فَقِيلَ لِي سَيِّدٌ بَنَى دَارًا فَصَنَعَ مَأْدُبَةً وَأَرْسَلَ دَاعِيًا فَمَنْ أَجَابَ الدَّاعِيَ دَخَلَ الدَّارَ وَأَكَلَ مِنْ الْمَأْدُبَةِ وَرَضِيَ عَنْهُ السَّيِّدُ وَمَنْ لَمْ يُجِبْ الدَّاعِيَ لَمْ يَدْخُلْ الدَّارَ وَلَمْ يَطْعَمْ مِنْ الْمَأْدُبَةِ وَسَخِطَ عَلَيْهِ السَّيِّدُ قَالَ فَاللَّهُ السَّيِّدُ وَمُحَمَّدٌ الدَّاعِي وَالدَّارُ الْإِسْلَامُ وَالْمَأْدُبَةُ الْجَنَّةُ",
    id : "Telah mengabarkan kepada kami [Mujahid bin Musa] telah menceritakan kepada kami [Raihan Ibnu Sa'id] telah menceritakan kepada kami ['Abbad Ibnu Mansur] dari [Ayyub] dari [Abu Qilabah] dari ['Athiyah] bahwasanya ia mendengar [Rabi'ah Al Jurasyi] berkata; Nabi shallallahu 'alaihi wasallam didatangkan lalu dikatakan kepada beliau, silahkan mata baginda tidur, telinga baginda mendengar, dan hati baginda berpikir. Beliau berkata: maka mata saya melihat, telinga saya mendengar, dan hati saya berpikir. Ia berkata; saya memperoleh informasi \"Ada seorang Tuan yang membangun rumah, lalu menyediakan jamuan, kemudian ia mengutus seorang untuk mengundang ke jamuan, barang siapa yang menyambut seruan penyeru dan memasuki rumah lalu makan hidangan maka baginda tersebut akan ridla kepadanya. Sebaliknya barang siapa yang tidak menyambut seruan penyeru dan tidak masuk ke rumah serta tidak makan hidangan, maka Tuan akan marah kepadanya. Lalu ia berkata: Tuan tersebut adalah Allah Subhanahu Wa Ta'ala, penyerunya adalah Muhammad shallallahu 'alaihi wasallam, rumahnya adalah Islam, dan hidangannya adalah surga. "
  ),
 Darimi(
    number : 12,
    arab : " أَخْبَرَنَا الْحَسَنُ بْنُ عَلِيٍّ حَدَّثَنَا أَبُو أُسَامَةَ عَنْ جَعْفَرِ بْنِ مَيْمُونٍ التَّمِيمِيِّ عَنْ أَبِي عُثْمَانَ النَّهْدِيِّ أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ خَرَجَ إِلَى الْبَطْحَاءِ وَمَعَهُ ابْنُ مَسْعُودٍ فَأَقْعَدَهُ وَخَطَّ عَلَيْهِ خَطًّا ثُمَّ قَالَ لَا تَبْرَحَنَّ فَإِنَّهُ سَيَنْتَهِي إِلَيْكَ رِجَالٌ فَلَا تُكَلِّمْهُمْ فَإِنَّهُمْ لَنْ يُكَلِّمُوكَ فَمَضَى رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ حَيْثُ أَرَادَ ثُمَّ جَعَلُوا يَنْتَهُونَ إِلَى الْخَطِّ لَا يُجَاوِزُونَهُ ثُمَّ يَصْدُرُونَ إِلَى النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ حَتَّى إِذَا كَانَ مِنْ آخِرِ اللَّيْلِ جَاءَ إِلَيَّ فَتَوَسَّدَ فَخِذِي وَكَانَ إِذَا نَامَ نَفَخَ فِي النَّوْمِ نَفْخًا فَبَيْنَا رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مُتَوَسِّدٌ فَخِذِي رَاقِدٌ إِذْ أَتَانِي رِجَالٌ كَأَنَّهُمْ الْجِمَالُ عَلَيْهِمْ ثِيَابٌ بِيضٌ اللَّهُ أَعْلَمُ مَا بِهِمْ مِنْ الْجَمَالِ حَتَّى قَعَدَ طَائِفَةٌ مِنْهُمْ عِنْدَ رَأْسِهِ وَطَائِفَةٌ مِنْهُمْ عِنْدَ رِجْلَيْهِ فَقَالُوا بَيْنَهُمْ مَا رَأَيْنَا عَبْدًا أُوتِيَ مِثْلَ مَا أُوتِيَ هَذَا النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ إِنَّ عَيْنَيْهِ لَتَنَامَانِ وَإِنَّ قَلْبَهُ لَيَقْظَانُ اضْرِبُوا لَهُ مَثَلًا سَيِّدٌ بَنَى قَصْرًا ثُمَّ جَعَلَ مَأْدُبَةً فَدَعَا النَّاسَ إِلَى طَعَامِهِ وَشَرَابِهِ ثُمَّ ارْتَفَعُوا وَاسْتَيْقَظَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ عِنْدَ ذَلِكَ فَقَالَ لِي أَتَدْرِي مَنْ هَؤُلَاءِ قُلْتُ اللَّهُ وَرَسُولُهُ أَعْلَمُ قَالَ هُمْ الْمَلَائِكَةُ قَالَ وَهَلْ تَدْرِي مَا الْمَثَلُ الَّذِي ضَرَبُوهُ قُلْتُ اللَّهُ وَرَسُولُهُ أَعْلَمُ قَالَ الرَّحْمَنُ بَنَى الْجَنَّةَ فَدَعَا إِلَيْهَا عِبَادَهُ فَمَنْ أَجَابَهُ دَخَلَ جَنَّتَهُ وَمَنْ لَمْ يُجِبْهُ عَاقَبَهُ وَعَذَّبَهُ",
    id : "Telah mengabarkan kepada kami [Al Hasan bin 'Ali] telah menceritakan kepada kami [Abu Usamah] dari [Ja'far bin Maimun At Tamimi] dari [Abu Utsman An Nahdi] Bahwa Rasulullah shallallahu 'alaihi wasallam keluar ke Bathha` dan bersamanya Ibnu Mas'ud Radliyallahu'anhu, lalu Rasulullah shallallahu 'alaihi wasallam pergi menuju Bathaa bersama ibnu Mas'ud, lalu beliau mengajak duduk Ibnu Mas'ud dan membuat satu garis pembatas untuknya. Lalu berkata: Jangan sekali-kali kamu tinggalkan tempat ini, karena beberapa orang laki-laki akan menemuimu yang kamu tidak berbicara kepada mereka, dan mereka pun tidak akan berbicara kepadamu. Lalu Rasulullah shallallahu 'alaihi wasallam meneruskan perjalanannya kemana saja beliau kehendaki. Kemudian sampailah orang-orang tersebut pada garis pembatas dan mereka tidak melewatinya, kemudian mereka pergi menuju Rasulullah shallallahu 'alaihi wasallam. Sampai ketika pada akhir malam beliau mendatangiku lalu tidur dengan menjadikan pahaku sebagai bantalnya, dan beliau apabila tidur terdengar hembusan nafasnya. Tatkala Rasulullah shallallahu 'alaihi wasallam sedang tidur di pahaku datanglah para lelaki seperti dengan paras yang tampan memakai pakaian yang serba putih. Huuh, alangkah indahnya mereka! sehingga segolongan dari mereka duduk di sisi kepala Rasulullah shallallahu 'alaihi wasallam dan segolongan yang lain di sisi kaminya lalu mereka saling berkata: kami belum pernah mendapatkan seorang hamba yang diberi anugerah seperti apa yang diberikan kepada Nabi shallallahu 'alaihi wasallam. Orang ini matanya tertidur tapi hatinya dalam keadaan sadar, buatlah baginya suatu perumpamaan. Baiklah, dia seperti seorang tuan yang membangun sebuah istana, kemudian membuat hidangan lalu mengundang orang-orang untuk makan dan minum, kemudian orang-orang tersebut naik ke langit. Lalu terbangunlah Rasulullah shallallahu 'alaihi wasallam ketika itu lalu beliau berkata kepadaku: tahukah kamu siapa mereka itu? lalu aku menjawab: Allah Subhanahu wa Ta'ala dan Rasul-Nya yang lebih tahu. Lalu beliau berkata: mereka adalah malaikat. Lalu beliau berkata lagi: tahukah anda apa yang diumpamakan? Aku katakan Allah Subhanahu wa Ta'ala dan Rasul-Nya yang lebih tahu beliau menjawab: Ar Rahman membangun surga, lalu menyeru (mengundang) hamba-hamba-Nya kepadanya, barang siapa yang menyambut maka dia akan masuk surga dan barang siapa yang menolak maka dia menghukum dan menyiksanya. "
  ),
 Darimi(
    number : 13,
    arab : " أَخْبَرَنَا نُعَيْمُ بْنُ حَمَّادٍ حَدَّثَنَا بَقِيَّةُ عَنْ بَحِيرٍ عَنْ خَالِدِ بْنِ مَعْدَانَ حَدَّثَنَا عَبْدُ الرَّحْمَنِ بْنُ عَمْرٍو السُّلَمِيُّ عَنْ عُتْبَةَ بْنِ عَبْدٍ السُّلَمِيِّ أَنَّهُ حَدَّثَهُمْ وَكَانَ مِنْ أَصْحَابِ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ لَهُ رَجُلٌ كَيْفَ كَانَ أَوَّلُ شَأْنِكَ يَا رَسُولَ اللَّهِ قَالَ كَانَتْ حَاضِنَتِي مِنْ بَنِي سَعْدِ بْنِ بَكْرٍ فَانْطَلَقْتُ أَنَا وَابْنٌ لَهَا فِي بَهْمٍ لَنَا وَلَمْ نَأْخُذْ مَعَنَا زَادًا فَقُلْتُ يَا أَخِي اذْهَبْ فَأْتِنَا بِزَادٍ مِنْ عِنْدِ أُمِّنَا فَانْطَلَقَ أَخِي وَمَكَثْتُ عِنْدَ الْبَهْمِ فَأَقْبَلَ طَائِرَانِ أَبْيَضَانِ كَأَنَّهُمَا نَسْرَانِ فَقَالَ أَحَدُهُمَا لِصَاحِبِهِ أَهُوَ هُوَ قَالَ الْآخَرُ نَعَمْ فَأَقْبَلَا يَبْتَدِرَانِي فَأَخَذَانِي فَبَطَحَانِي لِلْقَفَا فَشَقَّا بَطْنِي ثُمَّ اسْتَخْرَجَا قَلْبِي فَشَقَّاهُ فَأَخْرَجَا مِنْهُ عَلَقَتَيْنِ سَوْدَاوَيْنِ فَقَالَ أَحَدُهُمَا لِصَاحِبِهِ ائْتِنِي بِمَاءِ ثَلْجٍ فَغَسَلَ بِهِ جَوْفِي ثُمَّ قَالَ ائْتِنِي بِمَاءِ بَرَدٍ فَغَسَلَ بِهِ قَلْبِي ثُمَّ قَالَ ائْتِنِي بِالسَّكِينَةِ فَذَرَّهُ فِي قَلْبِي ثُمَّ قَالَ أَحَدُهُمَا لِصَاحِبِهِ حُصْهُ فَحَاصَهُ وَخَتَمَ عَلَيْهِ بِخَاتَمِ النُّبُوَّةِ ثُمَّ قَالَ أَحَدُهُمَا لِصَاحِبِهِ اجْعَلْهُ فِي كِفَّةٍ وَاجْعَلْ أَلْفًا مِنْ أُمَّتِهِ فِي كِفَّةٍ قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَإِذَا أَنَا أَنْظُرُ إِلَى الْأَلْفِ فَوْقِي أُشْفِقُ أَنْ يَخِرَّ عَلَيَّ بَعْضُهُمْ فَقَالَ لَوْ أَنَّ أُمَّتَهُ وُزِنَتْ بِهِ لَمَالَ بِهِمْ ثُمَّ انْطَلَقَا وَتَرَكَانِي قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَفَرِقْتُ فَرَقًا شَدِيدًا ثُمَّ انْطَلَقْتُ إِلَى أُمِّي فَأَخْبَرْتُهَا بِالَّذِي لَقِيتُ فَأَشْفَقَتْ أَنْ يَكُونَ قَدْ الْتَبَسَ بِي فَقَالَتْ أُعِيذُكَ بِاللَّهِ فَرَحَلَتْ بَعِيرًا لَهَا فَجَعَلَتْنِي عَلَى الرَّحْلِ وَرَكِبَتْ خَلْفِي حَتَّى بُلْغَتِنَا إِلَى أُمِّي فَقَالَتْ أَدَّيْتُ أَمَانَتِي وَذِمَّتِي وَحَدَّثَتْهَا بِالَّذِي لَقِيتُ فَلَمْ يَرُعْهَا ذَلِكَ وَقَالَتْ إِنِّي رَأَيْتُ حِينَ خَرَجَ مِنِّي يَعْنِي نُورًا أَضَاءَتْ مِنْهُ قُصُورُ الشَّامِ",
    id : "Telah mengabarkan kepada kami [Nu'aim bin Hammad] telah menceritakan kepada kami [Baqiyyah] dari [Bahir] dari [Khalid bin Ma'dan] telah menceritakan kepada kami ['Abdur Rahman bin 'Amr As Sulami] dari ['Utbah bin 'Abd As Sulami] Bahwa ia menceritakan kepada mereka, dan ia termasuk dari sahabat Rasulullah shallallahu 'alaihi wasallam, seorang laki-laki bertanya kepada Rasulullah shallallahu 'alaihi wasallam: Bagaimanakah perihal awal hidup baginda ya Rasulullah? beliau menjawab: Ibu asuhku ketika itu adalah perempuan Bani Sa'd bin Bakr ketika itu saya dan seorang anak kecil lainnya dari kabilah tersebut sedang menggembala binatang ternak. Karena kami tidak membawa bekal maka saya meminta kepada teman saya tersebut: wahai saudaraku pulanglah dan mintalah bekal kepada ibu kita. Lalu saudaraku pergi dan tinggal saya sendiri menjaga binatang ternak. Tiba-tiba datanglah dua burung yang putih seperti burung elang, salah satunya mengatakan kepada yang lain, apakah betul-betul dia? jawab yang lain; ya! lalu keduanya mengelilingi saya dan menarik saya serta menelentangkan saya, lalu mereka membelah perut saya kemudian mengeluarkan hati saya, membelahnya dan mengeluarkan dua gumpalan hitam. Kemudian berkatalah salah satu diantara keduanya kepada temannya: berikan saya air salju lalu dia pergunakan mencuci perut saya. Kemudian berkata lagi: berikan saya air sejuk\". Dan dia pergunakan mencuci hati saya. Kemudian dia berkata: berikan saya As Sakinah (ketenangan)! lalu dia menaburkannya dihati saya. Kemudian salah satunya berkata kepada temannya: jahitlah dia! lalu dijahitlah dan dia berikan tanda dengan khatam nubuwah (penutup para nabi). Kemudian berkata salah satu kepada temannya: letakkan dia pada salah satu timbangan dan letakkan seribu orang dari umatnya pada satu timbangan. Lalu Rasulullah shallallahu 'alaihi wasallam bersabda: ketika itu saya melihat seribu orang di atasku sehingga aku khawatir sebagian dari mereka jatuh menimpaku, lalu orang itu berkata lagi: seandainya umatnya ditimbang dengannya pasti akan lebih berat dia dari umatnya kemudian keduanya pergi meninggalkanku. Rasulullah shallallahu 'alaihi wasallam berkata: saya takut sekali kemudian saya berlari menuju ibu susuku dan saya beritahukan dia tentang apa yang baru saja terjadi padaku. Dia pun khawatir akan terjadi apa-apa terhadapku lalu dia berkata: aku meminta perlindungan Allah Subhanahu wa Ta'ala untukmu. Lalu dia mempersiapkan tunggangannya untuk pergi dan menempatkanku di atas onta dan dia naik di belakangku hingga kami sampai menjumpai ibuku, lalu dia berkata kepada ibuku: aku telah melaksanakan amanat dan beban yang telah dibebankan kepadaku, lalu dia menceritakan apa yang terjadi padaku. Namun hal itu tidak membuatnya gusar, bahkan ibuku menjawab: Dahulu malah saya melihatnya ketika dia baru keluar dari rahimku, yaitu cahaya yang menyinari singgasana Syam. "
  ),
 Darimi(
    number : 14,
    arab : " أَخْبَرَنَا عَبْدُ اللَّهِ بْنُ عِمْرَانَ حَدَّثَنَا أَبُو دَاوُدَ حَدَّثَنَا جَعْفَرُ بْنُ عُثْمَانَ الْقُرَشِيُّ عَنْ عُثْمَانَ بْنِ عُرْوَةَ بْنِ الزُّبَيْرِ عَنْ أَبِيهِ عَنْ أَبِي ذَرٍّ الْغِفَارِيِّ قَالَ قُلْتُ يَا رَسُولَ اللَّهِ كَيْفَ عَلِمْتَ أَنَّكَ نَبِيٌّ حَتَّى اسْتَيْقَنْتَ فَقَالَ يَا أَبَا ذَرٍّ أَتَانِي مَلَكَانِ وَأَنَا بِبَعْضِ بَطْحَاءِ مَكَّةَ فَوَقَعَ أَحَدُهُمَا عَلَى الْأَرْضِ وَكَانَ الْآخَرُ بَيْنَ السَّمَاءِ وَالْأَرْضِ فَقَالَ أَحَدُهُمَا لِصَاحِبِهِ أَهُوَ هُوَ قَالَ نَعَمْ قَالَ فَزِنْهُ بِرَجُلٍ فَوُزِنْتُ بِهِ فَوَزَنْتُهُ ثُمَّ قَالَ فَزِنْهُ بِعَشَرَةٍ فَوُزِنْتُ بِهِمْ فَرَجَحْتُهُمْ ثُمَّ قَالَ زِنْهُ بِمِائَةٍ فَوُزِنْتُ بِهِمْ فَرَجَحْتُهُمْ ثُمَّ قَالَ زِنْهُ بِأَلْفٍ فَوُزِنْتُ بِهِمْ فَرَجَحْتُهُمْ كَأَنِّي أَنْظُرُ إِلَيْهِمْ يَنْتَثِرُونَ عَلَيَّ مِنْ خِفَّةِ الْمِيزَانِ قَالَ فَقَالَ أَحَدُهُمَا لِصَاحِبِهِ لَوْ وَزَنْتَهُ بِأُمَّتِهِ لَرَجَحَهَا",
    id : "Telah mengabarkan kepada kami [Abdullah bin Imran] telah menceritakan kepada kami [Abu Daud] telah menceritakan kepada kami [Ja'far bin Utsman Al Qurasyi] dari [Utsman bin Urwah bin Az Zubair] dari [ayahnya] dari [Abu Dzar Al Ghifari] Radliyallahu'anhu, ia berkata; saya bertanya wahai Rasulullah bagaimana bisa yakin bahwa kamu adalah nabi? nabi menjawab: wahai Abu Dzar dua malaikat datang kepadaku ketika aku sedang berada di suatu lembah di Makkah. Salah satunya turun ke bumi dan yang lainnya berada diantara langit dan bumi. Salah satunya mengatakan kepada temannya: apakah benar-benar dia? lalu temannya menjawab: ya! lalu berkata lagi: kalau begitu timbanglah dia dengan seseorang, maka saya ditimbang dengan sepuluh orang dan saya lebih berat dari pada mereka. Kemudian berkata lagi: \"Timbanglah dia dengan seratus orang\", maka saya pun ditimbang dan saya lebih berat daripada mereka. Lalu berkata lagi: \"Kalau begitu timbanglah dengan seribu orang\", lalu saya pun ditimbang dan saya lebih berat dari mereka. Ketika itu saya seakan-akan melihat mereka berdesak-desakkan karena sempitnya timbangan kemudian salah satu diantara dua malaikat itu berkata kepada temannya: kalaupun dia ditimbang dengan seluruh umatnya maka dia akan tetap lebih berat dari mereka. "
  ),
 Darimi(
    number : 15,
    arab : " أَخْبَرَنَا إِسْمَعِيلُ بْنُ خَلِيلٍ حَدَّثَنَا عَلِيُّ بْنُ مُسْهِرٍ حَدَّثَنَا الْأَعْمَشُ عَنْ أَبِي صَالِحٍ قَالَ كَانَ النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يُنَادِيهِمْ يَا أَيُّهَا النَّاسُ إِنَّمَا أَنَا رَحْمَةٌ مُهْدَاةٌ",
    id : "Telah mengabarkan kepada kami [Ismail bin Khalil] telah menceritakan kepada kami [Ali bin Mushir] telah menceritakan kepada kami [Al A'masy] dari [Abu Shalih], ia berkata; Nabi shallallahu 'alaihi wasallam pernah memanggil mereka; wahai manusia sesungguhnya saya adalah rahmat dan mendapatkan petunjuk. "
  ),
];