class IbnuMajah{
  int? number;
  String? arab;
  String? id;

IbnuMajah({this.number, this.arab, this.id});
}

var dataHadits = [
   IbnuMajah(
    number : 1,
    arab : "حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ قَالَ حَدَّثَنَا شَرِيكٌ عَنْ الْأَعْمَشِ عَنْ أَبِي صَالِحٍ عَنْ أَبِي هُرَيْرَةَ قَالَقَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مَا أَمَرْتُكُمْ بِهِ فَخُذُوهُ وَمَا نَهَيْتُكُمْ عَنْهُ فَانْتَهُوا",
    id : "Telah menceritakan kepada kami [Abu Bakar bin Abu Syaibah] berkata; telah menceritakan kepada kami [Syarik] dari [Al A'masy] dari [Abu Shalih] dari [Abu Hurairah] ia berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \"Apa yang aku perintahkan maka ambillah, dan apa yang aku larang maka tinggalkanlah.\""
 ),
 IbnuMajah(
    number : 2,
    arab : "حَدَّثَنَا مُحَمَّدُ بْنُ الصَّبَّاحِ قَالَ أَنْبَأَنَا جَرِيرٌ عَنْ الْأَعْمَشِ عَنْ أَبِي صَالِحٍ عَنْ أَبِي هُرَيْرَةَ قَالَقَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ذَرُونِي مَا تَرَكْتُكُمْ فَإِنَّمَا هَلَكَ مَنْ كَانَ قَبْلَكُمْ بِسُؤَالِهِمْ وَاخْتِلَافِهِمْ عَلَى أَنْبِيَائِهِمْ فَإِذَا أَمَرْتُكُمْ بِشَيْءٍ فَخُذُوا مِنْهُ مَا اسْتَطَعْتُمْ وَإِذَا نَهَيْتُكُمْ عَنْ شَيْءٍ فَانْتَهُوا",
    id : "Telah menceritakan kepada kami [Muhammad bin Ash Shabbah] ia berkata; telah memberitakan kepada kami [Jarir] dari [Al A'masy] dari [Abu Shalih] dari [Abu Hurairah] ia berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \"Biarkanlah apa yang telah aku tinggalkan untuk kalian. Sesungguhnya orang-orang sebelum kalian binasa karena pertanyaan dan perselisihan mereka kepada para Nabinya. Jika aku perintahkan kepada kalian terhadap suatu perkara maka laksanakanlah semampu kalian, dan jika aku larang kalian dari suatu perkara maka jauhilah.\" "
 ),
 IbnuMajah(
    number : 3,
    arab : "حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ حَدَّثَنَا أَبُو مُعَاوِيَةَ وَوَكِيعٌ عَنْ الْأَعْمَشِ عَنْ أَبِي صَالِحٍ عَنْ أَبِي هُرَيْرَةَ قَالَقَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مَنْ أَطَاعَنِي فَقَدْ أَطَاعَ اللَّهَ وَمَنْ عَصَانِي فَقَدْ عَصَى اللَّهَ",
    id : "Telah menceritakan kepada kami [Abu Bakr bin Abu Syaibah] berkata, telah menceritakan kepada kami [Abu Mu'awiyah], dan [Waki'] dari [Al A'masy] dari [Abu Shalih] dari [Abu Hurairah] ia berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Barangsiapa menta'atiku maka ia telah ta'at kepada Allah dan barangsiapa durhaka kepadaku maka ia telah durhaka kepada Allah.\""
 ),
 IbnuMajah(
    number : 4,
    arab : "حَدَّثَنَا مُحَمَّدُ بْنُ عَبْدِ اللَّهِ بْنِ نُمَيْرٍ حَدَّثَنَا زَكَرِيَّا بْنُ عَدِيٍّ عَنْ ابْنِ الْمُبَارَكِ عَنْ مُحَمَّدِ بْنِ سُوقَةَ عَنْ أَبِي جَعْفَرٍ قَالَكَانَ ابْنُ عُمَرَ إِذَا سَمِعَ مِنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ حَدِيثًا لَمْ يَعْدُهُ وَلَمْ يُقَصِّرْ دُونَهُ",
    id : "Telah menceritakan kepada kami [Muhammad bin Abdullah bin Numair] berkata, telah menceritakan kepada kami [Zakaria bin 'Adi] dari [Ibnu Mubarak] dari [Muhammad bin Suqah] dari [Abu Ja'far] ia berkata; \" [Ibnu Umar] Jika mendengar sebuah hadits dari Rasulullah shallallahu 'alaihi wasallam, ia tidak melewatkannya dan tidak pula sibuk dengan yang lainnya.\" "
 ),
 IbnuMajah(
    number : 5,
    arab : "حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ الدِّمَشْقِيُّ حَدَّثَنَا مُحَمَّدُ بْنُ عِيسَى بْنِ سُمَيْعٍ حَدَّثَنَا إِبْرَاهِيمُ بْنُ سُلَيْمَانَ الْأَفْطَسُ عَنْ الْوَلِيدِ بْنِ عَبْدِ الرَّحْمَنِ الْجُرَشِيِّ عَنْ جُبَيْرِ بْنِ نُفَيْرٍ عَنْ أَبِي الدَّرْدَاءِ قَالَخَرَجَ عَلَيْنَا رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَنَحْنُ نَذْكُرُ الْفَقْرَ وَنَتَخَوَّفُهُ فَقَالَ أَالْفَقْرَ تَخَافُونَ وَالَّذِي نَفْسِي بِيَدِهِ لَتُصَبَّنَّ عَلَيْكُمْ الدُّنْيَا صَبًّا حَتَّى لَا يُزِيغَ قَلْبَ أَحَدِكُمْ إِزَاغَةً إِلَّا هِيهْ وَايْمُ اللَّهِ لَقَدْ تَرَكْتُكُمْ عَلَى مِثْلِ الْبَيْضَاءِ لَيْلُهَا وَنَهَارُهَا سَوَاءٌقَالَ أَبُو الدَّرْدَاءِ صَدَقَ وَاللَّهِ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ تَرَكَنَا وَاللَّهِ عَلَى مِثْلِ الْبَيْضَاءِ لَيْلُهَا وَنَهَارُهَا سَوَاءٌ",
    id : "Telah menceritakan kepada kami [Hisyam bin 'Ammar Ad Dimasyqi] berkata, telah menceritakan kepada kami [Muhammad bin Isa bin Sumai'] berkata, telah menceritakan kepada kami [Ibrahim bin Sulaiman Al Afthas] dari [Al Walid bin Abdurrahman Al Jurasyi] dari [Jubair bin Nufair] dari [Abu Darda`] ia berkata; \"Rasulullah shallallahu 'alaihi wasallam keluar menemui kami, sementara kami sedang memperbincangkan masalah kefaqiran dan kami merasa takut darinya. Lalu beliau bersabda: \" Apakah kalian takut kepada kemiskinan? Demi Dzat yang jiwaku berada di tangan-Nya, sungguh akan diberikan kepada kalian dunia, hingga hati salah seorang dari kalian tidak bisa berpaling kecuali akan menemuinya. Sungguh, telah aku tinggalkan untuk kalian perkara terang benderang, malam dan siangnya sama.\" Abu Darda` berkata; \"Demi Allah benar, Rasulullah shallallahu 'alaihi wasallam telah meniggalkan bagi kita perkara yang terang benderang, malam dan siangnya sama.\""
 ),
 IbnuMajah(
    number : 6,
    arab : "حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ حَدَّثَنَا مُحَمَّدُ بْنُ جَعْفَرٍ حَدَّثَنَا شُعْبَةُ عَنْ مُعَاوِيَةَ بْنِ قُرَّةَ عَنْ أَبِيهِ قَالَقَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ لَا تَزَالُ طَائِفَةٌ مِنْ أُمَّتِي مَنْصُورِينَ لَا يَضُرُّهُمْ مَنْ خَذَلَهُمْ حَتَّى تَقُومَ السَّاعَةُ",
    id : "Telah menceritakan kepada kami [Muhammad bin Basysyar] berkata, telah menceritakan kepada kami [Muhammad bin Ja'far] berkata, telah menceritakan kepada kami [Syu'bah] dari [Mu'awiyah bin Qurrah] dari [Bapaknya] ia berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Akan senantiasa ada sekelompok dari umatku mendapat pertolongan. Orang-orang yang menghinakannya tidak akan membahayakan mereka hingga terjadi hari kiamat.\""
 ),
 IbnuMajah(
    number : 7,
    arab : "حَدَّثَنَا أَبُو عَبْد اللَّهِ قَالَ حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ قَالَ حَدَّثَنَا يَحْيَى بْنُ حَمْزَةَ قَالَ حَدَّثَنَا أَبُو عَلْقَمَةَ نَصْرُ بْنُ عَلْقَمَةَ عَنْ عُمَيْرِ بْنِ الْأَسْوَدِ وَكَثِيرِ بْنِ مُرَّةَ الْحَضْرَمِيِّ عَنْ أَبِي هُرَيْرَةَأَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ لَا تَزَالُ طَائِفَةٌ مِنْ أُمَّتِي قَوَّامَةً عَلَى أَمْرِ اللَّهِ لَا يَضُرُّهَا مَنْ خَالَفَهَا",
    id : "Telah menceritakan kepada kami Abu Abdullah ia berkata; telah menceritakan kepada kami [Hisyam bin 'Ammar] ia berkata; telah menceritakan kepada kami [Yahya bin Hamzah] berkata; telah menceritakan kepada kami [Abu Alqamah Nashr bin Alqamah] dari [Umair Al Aswad] dan [Katsir bin Murrah Al Hadlrami] dari [Abu Hurairah] berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Akan senantiasa ada sekelompok dari umatku yang tegar berdiri di atas perintah Allah, tidak akan membahayakan mereka orang yang menyelisihinya.\""
 ),
 IbnuMajah(
    number : 8,
    arab : "حَدَّثَنَا أَبُو عَبْد اللَّهِ قَالَ حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ حَدَّثَنَا الْجَرَّاحُ بْنُ مَلِيحٍ حَدَّثَنَا بَكْرُ بْنُ زُرْعَةَ قَالَ سَمِعْتُ أَبَا عِنَبَةَ الْخَوْلَانِيَّ وَكَانَ قَدْ صَلَّى الْقِبْلَتَيْنِ مَعَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَسَمِعْتُ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَقُولُ لَا يَزَالُ اللَّهُ يَغْرِسُ فِي هَذَا الدِّينِ غَرْسًا يَسْتَعْمِلُهُمْ فِي طَاعَتِهِ",
    id : "Telah menceritakan kepada kami Abu Abdullah ia berkata; telah menceritakan kepada kami [Hisyam bin 'Ammar] berkata, telah menceritakan kepada kami [Al Jarrah bin Malih] berkata, telah menceritakan kepada kami [Bakr bin Zur'ah] ia berkata; aku mendengar [Abu 'Inabah Al Khaulani] dan ia adalah sahabat yang mengalami shalat menghadap dua kiblat bersama Rasulullah shallallahu 'alaihi wasallam, ia berkata; Aku mendengar Rasulullah shallallahu 'alaihi wasallam bersabda: \" Allah akan senantiasa menanam tanaman (pembaharu) dalam agama ini, yang akan Ia arahkan untuk ketaatan kepada-Nya.\""
 ),
 IbnuMajah(
    number : 10,
    arab : "حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ حَدَّثَنَا مُحَمَّدُ بْنُ شُعَيْبٍ حَدَّثَنَا سَعِيدُ بْنُ بَشِيرٍ عَنْ قَتَادَةَ عَنْ أَبِي قِلَابَةَ عَنْ أَبِي أَسْمَاءَ الرَّحَبِيِّ عَنْ ثَوْبَانَأَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ لَا تَزَالُ طَائِفَةٌ مِنْ أُمَّتِي عَلَى الْحَقِّ مَنْصُورِينَ لَا يَضُرُّهُمْ مَنْ خَالَفَهُمْ حَتَّى يَأْتِيَ أَمْرُ اللَّهِ عَزَّ وَجَلَّ",
    id : "Telah menceritakan kepada kami [Hisyam bin 'Ammar] berkata, telah menceritakan kepada kami [Muhammad bin Syu'aib] berkata, telah menceritakan kepada kami [Sa'id bin Basyir] dari [Qatadah] dari [Abu Qilabah] dari [Abu Asma` Ar Rahabi] dari [Tsauban] berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Akan senantiasa ada sekelompk dari umatku yang ditolong di atas kebenaran, tidak membahayakan mereka orang yang menyelisihinya hingga datang keputusan Allah.\" "
 ),
 IbnuMajah(
    number : 11,
    arab : "حَدَّثَنَا أَبُو سَعِيدٍ عَبْدُ اللَّهِ بْنُ سَعِيدٍ حَدَّثَنَا أَبُو خَالِدٍ الْأَحْمَرُ قَالَ سَمِعْتُ مُجَالِدًا يَذْكُرُ عَنْ الشَّعْبِيِّ عَنْ جَابِرِ بْنِ عَبْدِ اللَّهِ قَالَكُنَّا عِنْدَ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَخَطَّ خَطًّا وَخَطَّ خَطَّيْنِ عَنْ يَمِينِهِ وَخَطَّ خَطَّيْنِ عَنْ يَسَارِهِ ثُمَّ وَضَعَ يَدَهُ فِي الْخَطِّ الْأَوْسَطِ فَقَالَ هَذَا سَبِيلُ اللَّهِ ثُمَّ تَلَا هَذِهِ الْآيَةَ{ وَأَنَّ هَذَا صِرَاطِي مُسْتَقِيمًا فَاتَّبِعُوهُ وَلَا تَتَّبِعُوا السُّبُلَ فَتَفَرَّقَ بِكُمْ عَنْ سَبِيلِهِ }",
    id : "Telah menceritakan kepada kami [Abu Sa'id Abdullah bin Sa'id] berkata, telah menceritakan kepada kami [Abu Khalid Al Ahmar] ia berkata; aku mendengar [Mujalid] menyebutkan dari [Asy Sya'bi] dari [Jabir bin Abdullah] ia berkata; \"Kami berada di sisi Nabi shallallahu 'alaihi wasallam, beliau lalu membuat satu garis, kemudian membuat dua garis di sisi kanannya dan dua garis lagi di sisi kirinya. Kemudian beliau meletakkan tangannya di garis yang tengah seraya bersabda: \" Inilah jalan Allah.\" Kemudian beliau membaca ayat ini: \"Dan bahwa (yang Kami perintahkan) ini adalah jalan-Ku yang lurus, maka ikutilah dia; dan janganlah kamu mengikuti jalan-jalan (yang lain), karena jalan-jalan itu mencerai-beraikan kamu dari jalan-Nya.\""
 ),
 IbnuMajah(
    number : 12,
    arab : "حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ قَالَ حَدَّثَنَا زَيْدُ بْنُ الْحُبَابِ عَنْ مُعَاوِيَةَ بْنِ صَالِحٍ حَدَّثَنِي الْحَسَنُ بْنُ جَابِرٍ عَنْ الْمِقْدَامِ بْنِ مَعْدِيكَرِبَ الْكِنْدِيِّأَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ يُوشِكُ الرَّجُلُ مُتَّكِئًا عَلَى أَرِيكَتِهِ يُحَدَّثُ بِحَدِيثٍ مِنْ حَدِيثِي فَيَقُولُ بَيْنَنَا وَبَيْنَكُمْ كِتَابُ اللَّهِ عَزَّ وَجَلَّ مَا وَجَدْنَا فِيهِ مِنْ حَلَالٍ اسْتَحْلَلْنَاهُ وَمَا وَجَدْنَا فِيهِ مِنْ حَرَامٍ حَرَّمْنَاهُ أَلَّا وَإِنَّ مَا حَرَّمَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مِثْلُ مَا حَرَّمَ اللَّهُ",
    id : "Telah menceritakan kepada kami [Abu Bakr bin Abu Syaibah] berkata, ia berkata; telah menceritakan kepada kami [Zaid Ibnu Al Hubab] dari [Mu'awiyah bin Shalih] berkata, telah menceritakan kepadaku [Al Hasan bin Jabir] dari [Al Miqdam bin Ma'dikarib Al Kindi] berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Dikhawatirkan seseorang bersandaran di tempat duduknya, diceritakan kepadanya sebuah hadits dariku, namun ia berkata; 'Antara kami dan kalian adalah kitabullah 'azza wajalla. Apa yang kami temukan yang halal darinya maka kami menghalalkannya dan apa yang kami temukan yang haram darinya, maka kami mengharamkannya.' Ketahuilah, sesungguhnya apa yang diharamkan Rasulullah shallallahu 'alaihi wasallam adalah seperti yang diharamkan Allah.\""
 ),
 IbnuMajah(
    number : 13,
    arab : "حَدَّثَنَا نَصْرُ بْنُ عَلِيٍّ الْجَهْضَمِيُّ حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ فِي بَيْتِهِ أَنَا سَأَلْتُهُ عَنْ سَالِمٍ أَبِي النَّضْرِ ثُمَّ مَرَّ فِي الْحَدِيثِ قَالَ أَوْ زَيْدِ بْنِ أَسْلَمَ عَنْ عُبَيْدِ اللَّهِ بْنِ أَبِي رَافِعٍ عَنْ أَبِيهِأَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ لَا أُلْفِيَنَّ أَحَدَكُمْ مُتَّكِئًا عَلَى أَرِيكَتِهِ يَأْتِيهِ الْأَمْرُ مِمَّا أَمَرْتُ بِهِ أَوْ نَهَيْتُ عَنْهُ فَيَقُولُ لَا أَدْرِي مَا وَجَدْنَا فِي كِتَابِ اللَّهِ اتَّبَعْنَاهُ",
    id : "Telah menceritakan kepada kami [Nashr bin Ali Al Jahdlami] berkata, telah menceritakan kepada kami [Sufyan bin Uyainah] -aku bertanya kepadanya di rumahnya- dari [Salim Abu Al Nadlr] -kemudian ia membaca sebuah hadits-, ia berkata; atau [Zaid bin Aslam] dari [Ubaidullah bin Abu Rafi'] dari [Bapaknya] berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \"Sungguh, salah seorang dari kalian akan ditemui dalam keadaan duduk bersandaran di tempat duduknya, lalu datang kepadanya perintah dan laranganku, namun ia berkata; 'Aku tidak mengetahui, apa yang kami jumpai dalam kitabullah, maka kami mengikutinya.'\""
 ),
 IbnuMajah(
    number : 14,
    arab : "حَدَّثَنَا أَبُو مَرْوَانَ مُحَمَّدُ بْنُ عُثْمَانَ الْعُثْمَانِيُّ حَدَّثَنَا إِبْرَاهِيمُ بْنُ سَعْدِ بْنِ إِبْرَاهِيمَ بْنِ عَبْدِ الرَّحْمَنِ بْنِ عَوْفٍ عَنْ أَبِيهِ عَنْ الْقَاسِمِ بْنِ مُحَمَّدٍ عَنْ عَائِشَةَأَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ",
    id : "Telah menceritakan kepada kami [Abu Marwan Muhammad bin Utsman Al Utsmani] berkata, telah menceritakan kepada kami [Ibrahim bin Sa'd bin Ibrahim bin Abdurrahman bin Auf] dari [Bapaknya] dari [Al Qasim bin Muhammad] dari [Aisyah] berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: \" Barangsiapa membuat perkara baru dalam urusan kami yang tidak termasuk darinya maka dia tertolak.\""
 ),
 IbnuMajah(
    number : 15,
    arab : "حَدَّثَنَا مُحَمَّدُ بْنُ رُمْحِ بْنِ الْمُهَاجِرِ الْمِصْرِيُّ أَنْبَأَنَا اللَّيْثُ بْنُ سَعْدٍ عَنْ ابْنِ شِهَابٍ عَنْ عُرْوَةَ بْنِ الزُّبَيْرِ أَنَّ عَبْدَ اللَّهِ بْنَ الزُّبَيْرِ حَدَّثَهُأَنَّ رَجُلًا مِنْ الْأَنْصَارِ خَاصَمَ الزُّبَيْرَ عِنْدَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِي شِرَاجِ الْحَرَّةِ الَّتِي يَسْقُونَ بِهَا النَّخْلَ فَقَالَ الْأَنْصَارِيُّ سَرِّحْ الْمَاءَ يَمُرُّ فَأَبَى عَلَيْهِ فَاخْتَصَمَا عِنْدَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فَقَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ اسْقِ يَا زُبَيْرُ ثُمَّ أَرْسِلْ الْمَاءَ إِلَى جَارِكَ فَغَضِبَ الْأَنْصَارِيُّ فَقَالَ يَا رَسُولَ اللَّهِ أَنْ كَانَ ابْنَ عَمَّتِكَ فَتَلَوَّنَ وَجْهُ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ثُمَّ قَالَ يَا زُبَيْرُ اسْقِ ثُمَّ احْبِسْ الْمَاءَ حَتَّى يَرْجِعَ إِلَى الْجَدْرِ قَالَ فَقَالَ الزُّبَيْرُ وَاللَّهِ إِنِّي لَأَحْسِبُ هَذِهِ الْآيَةَ نَزَلَتْ فِي ذَلِكَ{ فَلَا وَرَبِّكَ لَا يُؤْمِنُونَ حَتَّى يُحَكِّمُوكَ فِيمَا شَجَرَ بَيْنَهُمْ ثُمَّ لَا يَجِدُوا فِي أَنْفُسِهِمْ حَرَجًا مِمَّا قَضَيْتَ وَيُسَلِّمُوا تَسْلِيمًا }",
    id : "Telah menceritakan kepada kami [Muhammad bin Rumh bin Al Muhajir Al Mishri] berkata, telah menceritakan kepada kami [Al Laist bin Sa'd] dari [Ibnu Syihab] dari [Urwah bin Az Zubair] bahwasanya [Abdullah bin Az Zubair] menceritakan kepadanya, bahwa seorang laki-laki Anshar mendebat Az Zubair di samping Rasulullah shallallahu 'alaihi wasallam tentang masalah pengairan yang biasa mereka gunakan untuk menyiram pohon kurma. Orang Anshar itu berkata; \"Biarkan air itu lewat, \" tetapi Az Zubair tidak mengindahkannya. Maka terjadilah perdebatan di antara keduanya di hadapan Rasulullah shallallahu 'alaihi wasallam. Maka Rasulullah shallallahu 'alaihi wasallam pun bersabda: \" Airilah (kebunmu) wahai Zubair, setelah itu Alirkan air tersebut untuk tetanggamu.\" Tetapi orang Anshar tersebut marah seraya berkata; \"Ya Rasulullah, apakah karena dia anak pamanmu?\" Maka berubahlah wajah Rasulullah shallallahu 'alaihi wasallam, lalu beliau bersabda: \"Hai Zubair, airilah (kebunmu), setelah itu tahan airnya agar ia kembali ke asalnya.\" Abdullah bin Zubair berkata; Maka Zubair berkata: \"Demi Allah saya mengira bahwa ayat ini turun dalam kejadian tersebut: \"Maka demi Rabbmu, mereka (pada hakekatnya) tidak beriman hingga mereka menjadikan kamu hakim dalam perkara yang mereka perselisihkan, kemudian mereka tidak merasa keberatan dalam hati mereka terhadap putusan yang kamu berikan, dan mereka menerima dengan sepenuhnya.\""
 ),
];